### PR TITLE
Step 4 test1

### PR DESCRIPTION
**Pull request by miyaliu627**
I optimized the process of prime factorization by reducing redundant factorization and using an array to store the already calculated info. I am not exactly sure how much headroom i have but i don't think there is a lot left for further optimization.

### CODE REVIEW

**Comment by minnce** [comment]
benchmark ss please

**Comment by miyaliu627** [comment]
Screenshot 2023-09-29 at 4 18 00 PM

**Review by minnce — CHANGES_REQUESTED** [review]
edit: might be stupid sec

**Comment by minnce** [comment]
My bad code is good to go for the first part of step 4 - please use up to 2500 for the second part.

**Comment by miyaliu627** [comment]
Screenshot 2023-09-29 at 4 36 25 PM

**Review by minnce — CHANGES_REQUESTED** [review]
slightly above 0.0001 - try to see if you can fit it within the allotted time

**Pull request merged**
